la-mia-pizzeria-razor-layout/Models/Pizza.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_razor_layout.Models
{
    [Table("pizza")]
    [Index(nameof(Name), IsUnique=true)]
    public class Pizza
    {
        [Key] public int PizzaId { get; set; }
        [Required(ErrorMessage ="Pizza name is mandatory")]
        [StringLength(25, ErrorMessage = "Pizza name has to be max 25 letters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Pizza description is mandatory")]
        [MinWords(5, ErrorMessage = "Description must contain at least 5 words.")]
        public string Description { get; set; }

        [Required(ErrorMessage ="Pizza photo is mandatory")]
        public string Photo { get; set; }

        [Price(ErrorMessage = "Invalid price format or value.")]
        public decimal Price { get; set; }

        public int? CategoryId { get; set; }
        public Category? Category { get; set; }

        public List<Ingredient>? Ingredients { get; set; }

        public Pizza() { }

        public Pizza(string name, string description, string photo, decimal price) : this()
        {
            this.Name = name;
            this.Description = description;
            this.Photo = photo;
            this.Price = price;
        }

        //public Pizza(int pizzaId, string name, string description, string photo, decimal price)
        //{
        //    PizzaId = pizzaId;
        //    Name = name;
        //    Description = description;
        //    Photo = photo;
        //    Price = price;
        //}

        public string GetDisplayedCategory()
        {
            if (Category == null)
                return "No category selected";
            return Category.Name;

        }
    }
}

la-mia-pizzeria-razor-layout/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using la_mia_pizzeria_razor_layout.Models;
using la_mia_pizzeria_razor_layout.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace la_mia_pizzeria_razor_layout.Controllers
{
    //[Authorize(Roles = "ADMIN,USER")]
    public class PizzaController : Controller
    {
        
        public IActionResult Index()
        {
            return View(PizzaManager.GetAllPizzas());
        }
        [Authorize(Roles = "ADMIN, USER")]
        public IActionResult Show(int id)
        {
            Pizza pizza = PizzaManager.GetPizzaById(id, true);
            if (pizza != null)
                return View(pizza);
            else
                return View("errore");
        }
        
        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Create() 
        {
            PizzaFormModel model = new PizzaFormModel();
            model.Pizza = new Pizza();
            model.Categories = PizzaManager.GetCategories();
            model.CreateIngredients();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]

        public IActionResult Create(PizzaFormModel data)
        {
            if (!ModelState.IsValid)
            {
                data.Categories = PizzaManager.GetCategories();
                data.CreateIngredients();
                return View("Create", data);
            }
       
            PizzaManager.InsertPizza(data.Pizza, data.SelectedIngredients);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "ADMIN")]

        public IActionResult Update(int id)
        {
            Pizza pizzaToEdit = PizzaManager.GetPizzaById(id);
            if (pizzaToEdit == null)
            {
                return NotFound();
            }
            else
            {
                PizzaFormModel model = new PizzaFormModel(pizzaToEdit, PizzaManager.GetCategories());
                model.CreateIngredients();
                return View(model);
            }
          
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]

        public IActionResult Update(int id, PizzaFormModel data)
        {
            if (!ModelState.IsValid)
            {
                data.Categories=PizzaManager.GetCategories();
                data.CreateIngredients();
                data.Pizza.PizzaId = id; //Ripasso l'id di data per evitare che al salvataggio vada alla pagina con ID "0"
                //List<Category> categories = PizzaManager.GetCategories();
                //data.Categories = categories;
                return View("Update", data);
            }

            if (PizzaManager.UpdatePizza(id, data.Pizza.Name, data.Pizza.Description, data.Pizza.Photo, data.Pizza.Price, data.Pizza.CategoryId, data.SelectedIngredients))
                return RedirectToAction("Index");
            else
                return NotFound();

            //bool result = PizzaManager.UpdatePizza(id, pizzaToEdit =>
            //{
            //    pizzaToEdit.Name = data.Pizza.Name;
            //    pizzaToEdit.Description = data.Pizza.Description;
            //    pizzaToEdit.Photo = data.Pizza.Photo;
            //    pizzaToEdit.Price = data.Pizza.Price;
            //    pizzaToEdit.CategoryId = data.Pizza.CategoryId;
            //    pizzaToEdit.Ingredients.Clear();
            //});

            //if (result == true)
            //    return RedirectToAction("Index");
            //else
            //    return NotFound(); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]

        public IActionResult Delete(int id)
        {
            if (PizzaManager.DeletePizza(id))
                return RedirectToAction("Index");
            else
                return NotFound();
        }
    }
}

la-mia-pizzeria-razor-layout/Views/Pizza/Create.cshtml
@model PizzaFormModel
<div class="show-pizza-wrapper">
    <div class="container mt-5 vh-100">
        <div class="d-flex justify-content-end mb-3">
            <a href="@Url.Action("Index", "Pizza")" class="btn btn-danger">Back to all Pizzas</a>
        </div>
        <div class="card p-4">
            <form asp-controller="Pizza" asp-action="Create" method="post">
            @Html.AntiForgeryToken()
                <div class="mb-3">
                    <label for="name" class="form-label text-danger">Name:</label>
                    <input asp-for="Pizza.Name" class="form-control" id="name" aria-describedby="name">
                    <span asp-validation-for="Pizza.Name" class="text-secondary"></span>
                </div>
                <div class="mb-3">
                    <label for="Description" class="form-label text-danger">Description:</label>
                    <input asp-for="Pizza.Description" class="form-control" id="Description" aria-describedby="description">
                    <span asp-validation-for="Pizza.Description" class="text-secondary"></span>
                </div>
                <div class="mb-3">
                    <label for="Photo" class="form-label text-danger">Photo:</label>
                    <input asp-for="Pizza.Photo" class="form-control" id="Photo" aria-describedby="photo">
                    <span asp-validation-for="Pizza.Photo" class="text-secondary"></span>
                </div>
                <div class="mb-3">
                    <label for="Price" class="form-label text-danger">Price:</label>
                    <input asp-for="Pizza.Price" class="form-control" id="Price" aria-describedby="price">
                    <span asp-validation-for="Pizza.Price" class="text-secondary"></span>
                </div>
                <div class="mb-3">
                    <label for="Category" class="text-danger">Category:</label>
                    <select asp-for="Pizza.CategoryId" rows="10" class="form-select" id="Category" aria-describedby="Category">
                        <option value=""></option>
                        @foreach (Category category in Model.Categories)
                        {
                            @if (Model.Pizza.CategoryId == category.Id)
                            {
                                <option value="@category.Id" selected>@category.Name</option>
                            }
                            else
                            {
                                <option value="@category.Id">@category.Name</option>
                            }
                        }
                    </select>

                </div>
                <div class="mb-3 d-flex flex-wrap">
                    @for (int i = 0; i < Model.Ingredients.Count; i++)
                    {
                        <div class="p-2">
                            <input class="checkbox" type="checkbox" name="SelectedIngredients" value="@Model.Ingredients[i].Value"
                            @(Model.SelectedIngredients.Contains(Model.Ingredients[i].Value) ? "checked" : "") />
                            @Model.Ingredients[i].Text
                        </div>
                    }
                </div>
                <button type="submit" class="btn btn-secondary">Save</button>
            </form>
        </div>
    </div>
</div>

la-mia-pizzeria-razor-layout/Views/Pizza/Index.cshtml
@using la_mia_pizzeria_razor_layout.Data
@model List<Pizza>
﻿@{
    using la_mia_pizzeria_razor_layout.Data.PizzaContext db = new PizzaContext();
    ViewData["Title"] = "La pizzeria di Giggino";
}

<div class="wrapper">
    <div class="container">
        <h1 class="text-center text-light p-4">Pizze disponibili</h1>
        <div class="row">
            <table class="table table-dark table-bordered">
                <thead>
                    <tr>
                        <th scope="col" class="text-center bg-danger">Name</th>
                        <th scope="col" class="text-center bg-danger">Image</th>
                        <th scope="col" class="text-center bg-danger">Price</th>
                        <th scope="col" class="text-center bg-danger">Description</th>
                        <th scope="col" class="text-center bg-danger">Details</th>
                        @if (User.IsInRole("ADMIN"))
                        {
                        <th scope="col" class="text-center bg-danger">Edit</th>
                        <th scope="col" class="text-center bg-danger">Delete</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @if (Model == null || !Model.Any())
                    {
                        <tr>
                            <td colspan="4" class="text-center">Non ci sono pizze disponibili al momento.</td>
                        </tr>
                    }
                    else
                    {
                        @foreach (Pizza pizza in Model)
                        {
                            <tr>
                                <td class="text-center align-content-center">@pizza.Name</td>
                                <td class="text-center align-content-center"><img src="@Url.Content(pizza.Photo)" class="img-thumbnail small-image" alt="@pizza.Name"></td>
                                <td class="text-center align-content-center">€ @pizza.Price</td>
                                <td class="text-center align-content-center">@pizza.Description</td>
                                <td class="text-center align-content-center">
                                    <button type="button" class="btn btn-danger">
                                        <a href="@Url.Action("Show", "Pizza", new { id = pizza.PizzaId })"><i class="bi bi-arrow-up-right-square"></i></a>
                                    </button>
                                </td>
                                @if (User.IsInRole("ADMIN"))
                                {
                                <td class="text-center align-content-center">
                                    <button type="button" class="btn btn-warning">
                                        <a href="@Url.Action("Update", "Pizza", new { id = pizza.PizzaId })"><i class="bi bi-pencil-square"></i></a>
                                    </button>
                                </td>
                                <td class="text-center align-content-center">
                                    <form asp-controller="Pizza" asp-action="Delete" asp-route-id="@pizza.PizzaId" method="post">
                                        @Html.AntiForgeryToken()
                                        <button type="submit" class="btn btn-success text-dark">
                                            <i class="bi bi-trash3"></i>
                                        </button>
                                    </form>
                                </td>
                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
            @if (User.IsInRole("ADMIN"))
            {
            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-outline-danger mb-5">
                    <a href="@Url.Action("Create","Pizza")">Add New Pizza</a>
                </button>
            </div>
            }
        </div>
    </div>
</div>

la-mia-pizzeria-razor-layout/Views/Pizza/Show.cshtml
@model Pizza

@{
    ViewData["Title"] = "Dettagli Pizza";
}

<div class="show-pizza-wrapper h-auto">
    <div class="container pizza-card-container">
        <div class="d-flex justify-content-end my-2">
            <a href="@Url.Action("Index", "Pizza")" class="btn btn-danger"><i class="bi bi-skip-backward"></i> Back to all Pizzas</a>
        </div>
        <div class="row">
            <div class="col">
                <div class="card pizza-card">
                    <div class="card-image">
                        <img src="@Url.Content(Model.Photo)" class="card-img-top" alt="@Model.Name">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title fs-1 text-center text-danger">@Model.Name - <span class="badge bg-dark">@($"{Model.GetDisplayedCategory()}")</span></h5>
                        <p class="card-text text-center">Description: @Model.Description</p>
                        <p class="card-text text-center"><small class="text-muted">Price: € @Model.Price</small></p>
                        
                    </div>
                    <div style="display: flex; flex-wrap: wrap; gap: 5px;">
                        @foreach (var ingredient in Model.Ingredients)
                        {
                            <div style="background-color: #AAAAAA; display: flex; justify-content: center; align-items: center;
                            border-radius: 3px; border-style: solid; border-color: #AAAAAA; padding: 2px;">
                                @ingredient.Name
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

la-mia-pizzeria-razor-layout/Views/Pizza/Update.cshtml
@model PizzaFormModel
<div class="show-pizza-wrapper">
    <div class="container mt-5 vh-100">
        <div class="d-flex justify-content-end mb-3">
            <a href="@Url.Action("Index", "Pizza")" class="btn btn-danger">Back to all Pizzas</a>
        </div>
        <div class="card p-4">
            <form asp-controller="Pizza" asp-action="Update" asp-route-id="@Model.Pizza.PizzaId" method="post">
                @Html.AntiForgeryToken()
                <div class="mb-3">
                    <label for="Pizza.name" class="form-label text-danger">Name:</label>
                    <input asp-for="Pizza.Name" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="Pizza.Description" class="form-label text-danger">Description:</label>
                    <input asp-for="Pizza.Description" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Description" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="Pizza.Photo" class="form-label text-danger">Photo:</label>
                    <input asp-for="Pizza.Photo" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Photo" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="Price" class="form-label text-danger">Price:</label>
                    <input asp-for="Pizza.Price" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Price" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="Category" class="text-danger">Category:</label>
                    <select asp-for="Pizza.CategoryId" rows="10" class="form-select" id="Category" aria-describedby="Category">
                        <option value=""></option>
                        @foreach (Category category in Model.Categories)
                        {
                            @if (Model.Pizza.CategoryId == category.Id)
                            {
                                <option value="@category.Id" selected>@category.Name</option>
                            }
                            else
                            {
                                <option value="@category.Id">@category.Name</option>
                            }
                        }
                    </select>
                </div>
                <div class="mb-3 d-flex flex-wrap">
                    @for (int i = 0; i < Model.Ingredients.Count; i++)
                    {
                        <div class="p-2">
                            <input class="checkbox" type="checkbox" name="SelectedIngredients" value="@Model.Ingredients[i].Value"
                            @(Model.SelectedIngredients.Contains(Model.Ingredients[i].Value) ? "checked" : "") />
                            @Model.Ingredients[i].Text
                        </div>
                    }
                </div>
                <div class="text-end">
                    <button type="submit" class="btn btn-secondary">
                        <i class="bi bi-floppy"></i> Salva
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>